export interface NewsEntry {
  id: string;
  type: "news";
  title: string;
  description: string;
  source: string;
  category: "Model Release" | "Vibe Coding" | "Industry" | "Culture" | "Research" | "Frontier";
  timestamp: string;
  url: string;
}

export const newsFeed: NewsEntry[] = [
  {
    id: "n1",
    type: "news",
    title: "Claude Opus 4.6 'Mythos' spotted in internal benchmarks — rumored multi-agent orchestration",
    description: "Anonymous sources say the new Opus variant can coordinate multiple sub-agents and plan across 100K+ token horizons.",
    source: "@ai_whispers",
    category: "Frontier",
    timestamp: "45m ago",
    url: "https://x.com",
  },
  {
    id: "n2",
    type: "news",
    title: "Anthropic quietly ships Claude 4.6 Sonnet — early testers say reasoning is 'terrifyingly good'",
    description: "The latest Sonnet update scores within 2% of Opus on SWE-bench while running 5x faster.",
    source: "Anthropic Blog",
    category: "Model Release",
    timestamp: "2h ago",
    url: "https://anthropic.com",
  },
  {
    id: "n3",
    type: "news",
    title: "Leaked Google internal memo: 'We are 6 months behind Anthropic on reasoning'",
    description: "A circulating internal doc admits Gemini's chain-of-thought capabilities trail Claude significantly.",
    source: "@dalrymple",
    category: "Frontier",
    timestamp: "3h ago",
    url: "https://x.com",
  },
  {
    id: "n4",
    type: "news",
    title: "GPT-5 internal codename 'Orion' reportedly achieves PhD-level performance across 12 domains",
    description: "Multiple sources confirm the model passes expert-level evaluations in law, medicine, physics, and more.",
    source: "The Information",
    category: "Frontier",
    timestamp: "4h ago",
    url: "https://theinformation.com",
  },
  {
    id: "n5",
    type: "news",
    title: "Solo dev ships $2M ARR SaaS in 6 weeks using only Claude Code — no prior coding experience",
    description: "A former product manager built and launched a billing platform without writing a single line manually.",
    source: "Hacker News",
    category: "Vibe Coding",
    timestamp: "5h ago",
    url: "https://news.ycombinator.com",
  },
  {
    id: "n6",
    type: "news",
    title: "DeepSeek V3 open weights drop — matches GPT-4o on coding at 1/10th the cost",
    description: "The Chinese lab releases a fully open model that undercuts every commercial API on price-performance.",
    source: "@deepseek_ai",
    category: "Model Release",
    timestamp: "6h ago",
    url: "https://deepseek.com",
  },
  {
    id: "n7",
    type: "news",
    title: "The vibe coding singularity: devs reporting AI writes 90%+ of their production code",
    description: "A growing cohort of developers say they now spend more time reviewing AI output than writing code.",
    source: "@levelsio",
    category: "Vibe Coding",
    timestamp: "7h ago",
    url: "https://x.com/levelsio",
  },
  {
    id: "n8",
    type: "news",
    title: "Cursor raises $900M Series C. AI coding tools market now valued at $30B+",
    description: "The AI-first editor has 4M daily users and is now the most valuable developer tools startup ever.",
    source: "Bloomberg",
    category: "Industry",
    timestamp: "8h ago",
    url: "https://bloomberg.com",
  },
  {
    id: "n9",
    type: "news",
    title: "OpenAI researcher hints at 'recursive self-improvement breakthroughs' in cryptic tweet",
    description: "The now-deleted post sent AI Twitter into a frenzy of speculation about what internal teams have achieved.",
    source: "@janleike",
    category: "Frontier",
    timestamp: "9h ago",
    url: "https://x.com",
  },
  {
    id: "n10",
    type: "news",
    title: "New paper: LLMs show emergent planning abilities not present in training data",
    description: "Researchers demonstrate that large models develop multi-step planning capabilities as an emergent property of scale.",
    source: "arXiv",
    category: "Research",
    timestamp: "10h ago",
    url: "https://arxiv.org",
  },
  {
    id: "n11",
    type: "news",
    title: "Anthropic CEO Dario Amodei: 'We may be 2-3 years from transformative AI'",
    description: "In a rare long-form interview, Amodei lays out a timeline that's shorter than most industry predictions.",
    source: "Lex Fridman Podcast",
    category: "Frontier",
    timestamp: "11h ago",
    url: "https://youtube.com",
  },
  {
    id: "n12",
    type: "news",
    title: "Claude Code agents now running 48-hour unsupervised coding sessions — the results are wild",
    description: "Developers share repos where autonomous agents refactored entire codebases overnight with zero human input.",
    source: "@alexalbert_",
    category: "Vibe Coding",
    timestamp: "12h ago",
    url: "https://x.com",
  },
  {
    id: "n13",
    type: "news",
    title: "Microsoft internal: Copilot generating 46% of all code across the company",
    description: "An internal productivity report reveals nearly half of all new code at Microsoft is now AI-generated.",
    source: "The Verge",
    category: "Industry",
    timestamp: "14h ago",
    url: "https://theverge.com",
  },
  {
    id: "n14",
    type: "news",
    title: "AI psychosis discourse explodes: therapists report surge in patients with AI dependency",
    description: "Mental health professionals document a new pattern of cognitive dependency on AI assistants for basic decisions.",
    source: "Wired",
    category: "Culture",
    timestamp: "16h ago",
    url: "https://wired.com",
  },
  {
    id: "n15",
    type: "news",
    title: "Llama 4 Behemoth leaked benchmarks suggest it rivals Claude Opus on reasoning tasks",
    description: "Unverified scores show Meta's unreleased flagship model closing the gap on Anthropic's best.",
    source: "@ai_explained",
    category: "Frontier",
    timestamp: "1d ago",
    url: "https://x.com",
  },
  {
    id: "n16",
    type: "news",
    title: "Former OpenAI alignment researcher: 'The scaling curves are not slowing down. Period.'",
    description: "A blunt assessment from someone who's seen the internal numbers and says the doubters are wrong.",
    source: "@janleike",
    category: "Frontier",
    timestamp: "1d ago",
    url: "https://x.com",
  },
  {
    id: "n17",
    type: "news",
    title: "Y Combinator W25: 80% of batch is solo founders using AI to build entire companies",
    description: "The accelerator's latest cohort is overwhelmingly one-person teams leveraging AI for engineering and ops.",
    source: "TechCrunch",
    category: "Vibe Coding",
    timestamp: "1d ago",
    url: "https://techcrunch.com",
  },
  {
    id: "n18",
    type: "news",
    title: "Chinese AI lab reportedly achieves ASI-level performance on narrow mathematical reasoning",
    description: "The claim is unverified but multiple credible researchers say the results they've seen are legitimate.",
    source: "@binabornosky",
    category: "Frontier",
    timestamp: "2d ago",
    url: "https://x.com",
  },
  {
    id: "n19",
    type: "news",
    title: "The 'AI whisperer' job title is now on LinkedIn. 12,000+ listings and counting.",
    description: "Prompt engineering has evolved into a recognized profession with six-figure salaries at major companies.",
    source: "Business Insider",
    category: "Culture",
    timestamp: "2d ago",
    url: "https://businessinsider.com",
  },
  {
    id: "n20",
    type: "news",
    title: "Nvidia H200 clusters hitting 90% utilization globally — compute shortage intensifying",
    description: "Demand for AI training compute continues to outstrip supply as every major lab races to scale.",
    source: "Reuters",
    category: "Industry",
    timestamp: "2d ago",
    url: "https://reuters.com",
  },
];
